<?xml version='1.0'?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!-- $Id$ -->
<!DOCTYPE encoding-set [
  <!ELEMENT encoding-set (encoding+)>
  <!ELEMENT encoding (glyph+)>
  <!ATTLIST encoding id ID #REQUIRED constant CDATA #REQUIRED glyphlist CDATA "AGL">
  <!ELEMENT glyph EMPTY>
  <!ATTLIST glyph codepoint CDATA #REQUIRED name CDATA #REQUIRED>
]>
<encoding-set>
  <encoding id='StandardEncoding' constant="STANDARD_ENCODING" glyphlist='AGL'>
    <glyph codepoint='20' name='space'/>
    <glyph codepoint='21' name='exclam'/>
    <glyph codepoint='22' name='quotedbl'/>
    <glyph codepoint='23' name='numbersign'/>
    <glyph codepoint='24' name='dollar'/>
    <glyph codepoint='25' name='percent'/>
    <glyph codepoint='26' name='ampersand'/>
    <glyph codepoint='27' name='quoteright'/>
    <glyph codepoint='28' name='parenleft'/>
    <glyph codepoint='29' name='parenright'/>
    <glyph codepoint='2a' name='asterisk'/>
    <glyph codepoint='2b' name='plus'/>
    <glyph codepoint='2c' name='comma'/>
    <glyph codepoint='2d' name='hyphen'/>
    <glyph codepoint='2e' name='period'/>
    <glyph codepoint='2f' name='slash'/>
    <glyph codepoint='30' name='zero'/>
    <glyph codepoint='31' name='one'/>
    <glyph codepoint='32' name='two'/>
    <glyph codepoint='33' name='three'/>
    <glyph codepoint='34' name='four'/>
    <glyph codepoint='35' name='five'/>
    <glyph codepoint='36' name='six'/>
    <glyph codepoint='37' name='seven'/>
    <glyph codepoint='38' name='eight'/>
    <glyph codepoint='39' name='nine'/>
    <glyph codepoint='3a' name='colon'/>
    <glyph codepoint='3b' name='semicolon'/>
    <glyph codepoint='3c' name='less'/>
    <glyph codepoint='3d' name='equal'/>
    <glyph codepoint='3e' name='greater'/>
    <glyph codepoint='3f' name='question'/>
    <glyph codepoint='40' name='at'/>
    <glyph codepoint='41' name='A'/>
    <glyph codepoint='42' name='B'/>
    <glyph codepoint='43' name='C'/>
    <glyph codepoint='44' name='D'/>
    <glyph codepoint='45' name='E'/>
    <glyph codepoint='46' name='F'/>
    <glyph codepoint='47' name='G'/>
    <glyph codepoint='48' name='H'/>
    <glyph codepoint='49' name='I'/>
    <glyph codepoint='4a' name='J'/>
    <glyph codepoint='4b' name='K'/>
    <glyph codepoint='4c' name='L'/>
    <glyph codepoint='4d' name='M'/>
    <glyph codepoint='4e' name='N'/>
    <glyph codepoint='4f' name='O'/>
    <glyph codepoint='50' name='P'/>
    <glyph codepoint='51' name='Q'/>
    <glyph codepoint='52' name='R'/>
    <glyph codepoint='53' name='S'/>
    <glyph codepoint='54' name='T'/>
    <glyph codepoint='55' name='U'/>
    <glyph codepoint='56' name='V'/>
    <glyph codepoint='57' name='W'/>
    <glyph codepoint='58' name='X'/>
    <glyph codepoint='59' name='Y'/>
    <glyph codepoint='5a' name='Z'/>
    <glyph codepoint='5b' name='bracketleft'/>
    <glyph codepoint='5c' name='backslash'/>
    <glyph codepoint='5d' name='bracketright'/>
    <glyph codepoint='5e' name='asciicircum'/>
    <glyph codepoint='5f' name='underscore'/>
    <glyph codepoint='60' name='quoteleft'/>
    <glyph codepoint='61' name='a'/>
    <glyph codepoint='62' name='b'/>
    <glyph codepoint='63' name='c'/>
    <glyph codepoint='64' name='d'/>
    <glyph codepoint='65' name='e'/>
    <glyph codepoint='66' name='f'/>
    <glyph codepoint='67' name='g'/>
    <glyph codepoint='68' name='h'/>
    <glyph codepoint='69' name='i'/>
    <glyph codepoint='6a' name='j'/>
    <glyph codepoint='6b' name='k'/>
    <glyph codepoint='6c' name='l'/>
    <glyph codepoint='6d' name='m'/>
    <glyph codepoint='6e' name='n'/>
    <glyph codepoint='6f' name='o'/>
    <glyph codepoint='70' name='p'/>
    <glyph codepoint='71' name='q'/>
    <glyph codepoint='72' name='r'/>
    <glyph codepoint='73' name='s'/>
    <glyph codepoint='74' name='t'/>
    <glyph codepoint='75' name='u'/>
    <glyph codepoint='76' name='v'/>
    <glyph codepoint='77' name='w'/>
    <glyph codepoint='78' name='x'/>
    <glyph codepoint='79' name='y'/>
    <glyph codepoint='7a' name='z'/>
    <glyph codepoint='7b' name='braceleft'/>
    <glyph codepoint='7c' name='bar'/>
    <glyph codepoint='7d' name='braceright'/>
    <glyph codepoint='7e' name='asciitilde'/>
    <glyph codepoint='a1' name='exclamdown'/>
    <glyph codepoint='a2' name='cent'/>
    <glyph codepoint='a3' name='sterling'/>
    <glyph codepoint='a4' name='fraction'/>
    <glyph codepoint='a5' name='yen'/>
    <glyph codepoint='a6' name='florin'/>
    <glyph codepoint='a7' name='section'/>
    <glyph codepoint='a8' name='currency'/>
    <glyph codepoint='a9' name='quotesingle'/>
    <glyph codepoint='aa' name='quotedblleft'/>
    <glyph codepoint='ab' name='guillemotleft'/>
    <glyph codepoint='ac' name='guilsinglleft'/>
    <glyph codepoint='ad' name='guilsinglright'/>
    <glyph codepoint='ae' name='fi'/>
    <glyph codepoint='af' name='fl'/>
    <glyph codepoint='b1' name='endash'/>
    <glyph codepoint='b2' name='dagger'/>
    <glyph codepoint='b3' name='daggerdbl'/>
    <glyph codepoint='b4' name='periodcentered'/>
    <glyph codepoint='b6' name='paragraph'/>
    <glyph codepoint='b7' name='bullet'/>
    <glyph codepoint='b8' name='quotesinglbase'/>
    <glyph codepoint='b9' name='quotedblbase'/>
    <glyph codepoint='ba' name='quotedblright'/>
    <glyph codepoint='bb' name='guillemotright'/>
    <glyph codepoint='bc' name='ellipsis'/>
    <glyph codepoint='bd' name='perthousand'/>
    <glyph codepoint='bf' name='questiondown'/>
    <glyph codepoint='c1' name='grave'/>
    <glyph codepoint='c2' name='acute'/>
    <glyph codepoint='c3' name='circumflex'/>
    <glyph codepoint='c4' name='tilde'/>
    <glyph codepoint='c5' name='macron'/>
    <glyph codepoint='c6' name='breve'/>
    <glyph codepoint='c7' name='dotaccent'/>
    <glyph codepoint='c8' name='dieresis'/>
    <glyph codepoint='ca' name='ring'/>
    <glyph codepoint='cb' name='cedilla'/>
    <glyph codepoint='cd' name='hungarumlaut'/>
    <glyph codepoint='ce' name='ogonek'/>
    <glyph codepoint='cf' name='caron'/>
    <glyph codepoint='d0' name='emdash'/>
    <glyph codepoint='e1' name='AE'/>
    <glyph codepoint='e3' name='ordfeminine'/>
    <glyph codepoint='e8' name='Lslash'/>
    <glyph codepoint='e9' name='Oslash'/>
    <glyph codepoint='ea' name='OE'/>
    <glyph codepoint='eb' name='ordmasculine'/>
    <glyph codepoint='f1' name='ae'/>
    <glyph codepoint='f5' name='dotlessi'/>
    <glyph codepoint='f8' name='lslash'/>
    <glyph codepoint='f9' name='oslash'/>
    <glyph codepoint='fa' name='oe'/>
    <glyph codepoint='fb' name='germandbls'/>
  </encoding>
  <encoding id='ISOLatin1Encoding' constant="ISOLATIN1_ENCODING" glyphlist='AGL'>
    <glyph codepoint='20' name='space'/>
    <glyph codepoint='21' name='exclam'/>
    <glyph codepoint='22' name='quotedbl'/>
    <glyph codepoint='23' name='numbersign'/>
    <glyph codepoint='24' name='dollar'/>
    <glyph codepoint='25' name='percent'/>
    <glyph codepoint='26' name='ampersand'/>
    <glyph codepoint='27' name='quoteright'/>
    <glyph codepoint='28' name='parenleft'/>
    <glyph codepoint='29' name='parenright'/>
    <glyph codepoint='2a' name='asterisk'/>
    <glyph codepoint='2b' name='plus'/>
    <glyph codepoint='2c' name='comma'/>
    <glyph codepoint='2d' name='minus'/>
    <glyph codepoint='2e' name='period'/>
    <glyph codepoint='2f' name='slash'/>
    <glyph codepoint='30' name='zero'/>
    <glyph codepoint='31' name='one'/>
    <glyph codepoint='32' name='two'/>
    <glyph codepoint='33' name='three'/>
    <glyph codepoint='34' name='four'/>
    <glyph codepoint='35' name='five'/>
    <glyph codepoint='36' name='six'/>
    <glyph codepoint='37' name='seven'/>
    <glyph codepoint='38' name='eight'/>
    <glyph codepoint='39' name='nine'/>
    <glyph codepoint='3a' name='colon'/>
    <glyph codepoint='3b' name='semicolon'/>
    <glyph codepoint='3c' name='less'/>
    <glyph codepoint='3d' name='equal'/>
    <glyph codepoint='3e' name='greater'/>
    <glyph codepoint='3f' name='question'/>
    <glyph codepoint='40' name='at'/>
    <glyph codepoint='41' name='A'/>
    <glyph codepoint='42' name='B'/>
    <glyph codepoint='43' name='C'/>
    <glyph codepoint='44' name='D'/>
    <glyph codepoint='45' name='E'/>
    <glyph codepoint='46' name='F'/>
    <glyph codepoint='47' name='G'/>
    <glyph codepoint='48' name='H'/>
    <glyph codepoint='49' name='I'/>
    <glyph codepoint='4a' name='J'/>
    <glyph codepoint='4b' name='K'/>
    <glyph codepoint='4c' name='L'/>
    <glyph codepoint='4d' name='M'/>
    <glyph codepoint='4e' name='N'/>
    <glyph codepoint='4f' name='O'/>
    <glyph codepoint='50' name='P'/>
    <glyph codepoint='51' name='Q'/>
    <glyph codepoint='52' name='R'/>
    <glyph codepoint='53' name='S'/>
    <glyph codepoint='54' name='T'/>
    <glyph codepoint='55' name='U'/>
    <glyph codepoint='56' name='V'/>
    <glyph codepoint='57' name='W'/>
    <glyph codepoint='58' name='X'/>
    <glyph codepoint='59' name='Y'/>
    <glyph codepoint='5a' name='Z'/>
    <glyph codepoint='5b' name='bracketleft'/>
    <glyph codepoint='5c' name='backslash'/>
    <glyph codepoint='5d' name='bracketright'/>
    <glyph codepoint='5e' name='asciicircum'/>
    <glyph codepoint='5f' name='underscore'/>
    <glyph codepoint='60' name='quoteleft'/>
    <glyph codepoint='61' name='a'/>
    <glyph codepoint='62' name='b'/>
    <glyph codepoint='63' name='c'/>
    <glyph codepoint='64' name='d'/>
    <glyph codepoint='65' name='e'/>
    <glyph codepoint='66' name='f'/>
    <glyph codepoint='67' name='g'/>
    <glyph codepoint='68' name='h'/>
    <glyph codepoint='69' name='i'/>
    <glyph codepoint='6a' name='j'/>
    <glyph codepoint='6b' name='k'/>
    <glyph codepoint='6c' name='l'/>
    <glyph codepoint='6d' name='m'/>
    <glyph codepoint='6e' name='n'/>
    <glyph codepoint='6f' name='o'/>
    <glyph codepoint='70' name='p'/>
    <glyph codepoint='71' name='q'/>
    <glyph codepoint='72' name='r'/>
    <glyph codepoint='73' name='s'/>
    <glyph codepoint='74' name='t'/>
    <glyph codepoint='75' name='u'/>
    <glyph codepoint='76' name='v'/>
    <glyph codepoint='77' name='w'/>
    <glyph codepoint='78' name='x'/>
    <glyph codepoint='79' name='y'/>
    <glyph codepoint='7a' name='z'/>
    <glyph codepoint='7b' name='braceleft'/>
    <glyph codepoint='7c' name='bar'/>
    <glyph codepoint='7d' name='braceright'/>
    <glyph codepoint='7e' name='asciitilde'/>
    <glyph codepoint='90' name='dotlessi'/>
    <glyph codepoint='91' name='grave'/>
    <glyph codepoint='93' name='circumflex'/>
    <glyph codepoint='94' name='tilde'/>
    <glyph codepoint='96' name='breve'/>
    <glyph codepoint='97' name='dotaccent'/>
    <glyph codepoint='9a' name='ring'/>
    <glyph codepoint='9d' name='hungarumlaut'/>
    <glyph codepoint='9e' name='ogonek'/>
    <glyph codepoint='9f' name='caron'/>
    <glyph codepoint='a1' name='exclamdown'/>
    <glyph codepoint='a2' name='cent'/>
    <glyph codepoint='a3' name='sterling'/>
    <glyph codepoint='a4' name='currency'/>
    <glyph codepoint='a5' name='yen'/>
    <glyph codepoint='a6' name='brokenbar'/>
    <glyph codepoint='a7' name='section'/>
    <glyph codepoint='a8' name='dieresis'/>
    <glyph codepoint='a9' name='copyright'/>
    <glyph codepoint='aa' name='ordfeminine'/>
    <glyph codepoint='ab' name='guillemotleft'/>
    <glyph codepoint='ac' name='logicalnot'/>
    <glyph codepoint='ad' name='softhyphen'/>
    <glyph codepoint='ae' name='registered'/>
    <glyph codepoint='af' name='macron'/>
    <glyph codepoint='b0' name='degree'/>
    <glyph codepoint='b1' name='plusminus'/>
    <glyph codepoint='b2' name='twosuperior'/>
    <glyph codepoint='b3' name='threesuperior'/>
    <glyph codepoint='b4' name='acute'/>
    <glyph codepoint='b5' name='mu'/>
    <glyph codepoint='b6' name='paragraph'/>
    <glyph codepoint='b7' name='periodcentered'/>
    <glyph codepoint='b8' name='cedilla'/>
    <glyph codepoint='b9' name='onesuperior'/>
    <glyph codepoint='ba' name='ordmasculine'/>
    <glyph codepoint='bb' name='guillemotright'/>
    <glyph codepoint='bc' name='onequarter'/>
    <glyph codepoint='bd' name='onehalf'/>
    <glyph codepoint='be' name='threequarters'/>
    <glyph codepoint='bf' name='questiondown'/>
    <glyph codepoint='c0' name='Agrave'/>
    <glyph codepoint='c1' name='Aacute'/>
    <glyph codepoint='c2' name='Acircumflex'/>
    <glyph codepoint='c3' name='Atilde'/>
    <glyph codepoint='c4' name='Adieresis'/>
    <glyph codepoint='c5' name='Aring'/>
    <glyph codepoint='c6' name='AE'/>
    <glyph codepoint='c7' name='Ccedilla'/>
    <glyph codepoint='c8' name='Egrave'/>
    <glyph codepoint='c9' name='Eacute'/>
    <glyph codepoint='ca' name='Ecircumflex'/>
    <glyph codepoint='cb' name='Edieresis'/>
    <glyph codepoint='cc' name='Igrave'/>
    <glyph codepoint='cd' name='Iacute'/>
    <glyph codepoint='ce' name='Icircumflex'/>
    <glyph codepoint='cf' name='Idieresis'/>
    <glyph codepoint='d0' name='Eth'/>
    <glyph codepoint='d1' name='Ntilde'/>
    <glyph codepoint='d2' name='Ograve'/>
    <glyph codepoint='d3' name='Oacute'/>
    <glyph codepoint='d4' name='Ocircumflex'/>
    <glyph codepoint='d5' name='Otilde'/>
    <glyph codepoint='d6' name='Odieresis'/>
    <glyph codepoint='d7' name='multiply'/>
    <glyph codepoint='d8' name='Oslash'/>
    <glyph codepoint='d9' name='Ugrave'/>
    <glyph codepoint='da' name='Uacute'/>
    <glyph codepoint='db' name='Ucircumflex'/>
    <glyph codepoint='dc' name='Udieresis'/>
    <glyph codepoint='dd' name='Yacute'/>
    <glyph codepoint='de' name='Thorn'/>
    <glyph codepoint='df' name='germandbls'/>
    <glyph codepoint='e0' name='agrave'/>
    <glyph codepoint='e1' name='aacute'/>
    <glyph codepoint='e2' name='acircumflex'/>
    <glyph codepoint='e3' name='atilde'/>
    <glyph codepoint='e4' name='adieresis'/>
    <glyph codepoint='e5' name='aring'/>
    <glyph codepoint='e6' name='ae'/>
    <glyph codepoint='e7' name='ccedilla'/>
    <glyph codepoint='e8' name='egrave'/>
    <glyph codepoint='e9' name='eacute'/>
    <glyph codepoint='ea' name='ecircumflex'/>
    <glyph codepoint='eb' name='edieresis'/>
    <glyph codepoint='ec' name='igrave'/>
    <glyph codepoint='ed' name='iacute'/>
    <glyph codepoint='ee' name='icircumflex'/>
    <glyph codepoint='ef' name='idieresis'/>
    <glyph codepoint='f0' name='eth'/>
    <glyph codepoint='f1' name='ntilde'/>
    <glyph codepoint='f2' name='ograve'/>
    <glyph codepoint='f3' name='oacute'/>
    <glyph codepoint='f4' name='ocircumflex'/>
    <glyph codepoint='f5' name='otilde'/>
    <glyph codepoint='f6' name='odieresis'/>
    <glyph codepoint='f7' name='divide'/>
    <glyph codepoint='f8' name='oslash'/>
    <glyph codepoint='f9' name='ugrave'/>
    <glyph codepoint='fa' name='uacute'/>
    <glyph codepoint='fb' name='ucircumflex'/>
    <glyph codepoint='fc' name='udieresis'/>
    <glyph codepoint='fd' name='yacute'/>
    <glyph codepoint='fe' name='thorn'/>
    <glyph codepoint='ff' name='ydieresis'/>
  </encoding>
  <encoding id='CEEncoding' constant="CE_ENCODING" glyphlist='AGL'>
    <glyph codepoint='20' name='space'/>
    <glyph codepoint='21' name='exclam'/>
    <glyph codepoint='22' name='quotedbl'/>
    <glyph codepoint='23' name='numbersign'/>
    <glyph codepoint='24' name='dollar'/>
    <glyph codepoint='25' name='percent'/>
    <glyph codepoint='26' name='ampersand'/>
    <glyph codepoint='27' name='quotesingle'/>
    <glyph codepoint='28' name='parenleft'/>
    <glyph codepoint='29' name='parenright'/>
    <glyph codepoint='2a' name='asterisk'/>
    <glyph codepoint='2b' name='plus'/>
    <glyph codepoint='2c' name='comma'/>
    <glyph codepoint='2d' name='hyphen'/>
    <glyph codepoint='2e' name='period'/>
    <glyph codepoint='2f' name='slash'/>
    <glyph codepoint='30' name='zero'/>
    <glyph codepoint='31' name='one'/>
    <glyph codepoint='32' name='two'/>
    <glyph codepoint='33' name='three'/>
    <glyph codepoint='34' name='four'/>
    <glyph codepoint='35' name='five'/>
    <glyph codepoint='36' name='six'/>
    <glyph codepoint='37' name='seven'/>
    <glyph codepoint='38' name='eight'/>
    <glyph codepoint='39' name='nine'/>
    <glyph codepoint='3a' name='colon'/>
    <glyph codepoint='3b' name='semicolon'/>
    <glyph codepoint='3c' name='less'/>
    <glyph codepoint='3d' name='equal'/>
    <glyph codepoint='3e' name='greater'/>
    <glyph codepoint='3f' name='question'/>
    <glyph codepoint='40' name='at'/>
    <glyph codepoint='41' name='A'/>
    <glyph codepoint='42' name='B'/>
    <glyph codepoint='43' name='C'/>
    <glyph codepoint='44' name='D'/>
    <glyph codepoint='45' name='E'/>
    <glyph codepoint='46' name='F'/>
    <glyph codepoint='47' name='G'/>
    <glyph codepoint='48' name='H'/>
    <glyph codepoint='49' name='I'/>
    <glyph codepoint='4a' name='J'/>
    <glyph codepoint='4b' name='K'/>
    <glyph codepoint='4c' name='L'/>
    <glyph codepoint='4d' name='M'/>
    <glyph codepoint='4e' name='N'/>
    <glyph codepoint='4f' name='O'/>
    <glyph codepoint='50' name='P'/>
    <glyph codepoint='51' name='Q'/>
    <glyph codepoint='52' name='R'/>
    <glyph codepoint='53' name='S'/>
    <glyph codepoint='54' name='T'/>
    <glyph codepoint='55' name='U'/>
    <glyph codepoint='56' name='V'/>
    <glyph codepoint='57' name='W'/>
    <glyph codepoint='58' name='X'/>
    <glyph codepoint='59' name='Y'/>
    <glyph codepoint='5a' name='Z'/>
    <glyph codepoint='5b' name='bracketleft'/>
    <glyph codepoint='5c' name='backslash'/>
    <glyph codepoint='5d' name='bracketright'/>
    <glyph codepoint='5e' name='asciicircum'/>
    <glyph codepoint='5f' name='underscore'/>
    <glyph codepoint='60' name='grave'/>
    <glyph codepoint='61' name='a'/>
    <glyph codepoint='62' name='b'/>
    <glyph codepoint='63' name='c'/>
    <glyph codepoint='64' name='d'/>
    <glyph codepoint='65' name='e'/>
    <glyph codepoint='66' name='f'/>
    <glyph codepoint='67' name='g'/>
    <glyph codepoint='68' name='h'/>
    <glyph codepoint='69' name='i'/>
    <glyph codepoint='6a' name='j'/>
    <glyph codepoint='6b' name='k'/>
    <glyph codepoint='6c' name='l'/>
    <glyph codepoint='6d' name='m'/>
    <glyph codepoint='6e' name='n'/>
    <glyph codepoint='6f' name='o'/>
    <glyph codepoint='70' name='p'/>
    <glyph codepoint='71' name='q'/>
    <glyph codepoint='72' name='r'/>
    <glyph codepoint='73' name='s'/>
    <glyph codepoint='74' name='t'/>
    <glyph codepoint='75' name='u'/>
    <glyph codepoint='76' name='v'/>
    <glyph codepoint='77' name='w'/>
    <glyph codepoint='78' name='x'/>
    <glyph codepoint='79' name='y'/>
    <glyph codepoint='7a' name='z'/>
    <glyph codepoint='7b' name='braceleft'/>
    <glyph codepoint='7c' name='bar'/>
    <glyph codepoint='7d' name='braceright'/>
    <glyph codepoint='7e' name='asciitilde'/>
    <glyph codepoint='82' name='quotesinglbase'/>
    <glyph codepoint='84' name='quotedblbase'/>
    <glyph codepoint='85' name='ellipsis'/>
    <glyph codepoint='86' name='dagger'/>
    <glyph codepoint='87' name='daggerdbl'/>
    <glyph codepoint='89' name='perthousand'/>
    <glyph codepoint='8a' name='Scaron'/>
    <glyph codepoint='8b' name='guilsinglleft'/>
    <glyph codepoint='8c' name='Sacute'/>
    <glyph codepoint='8d' name='Tcaron'/>
    <glyph codepoint='8e' name='Zcaron'/>
    <glyph codepoint='8f' name='Zacute'/>
    <glyph codepoint='91' name='quoteleft'/>
    <glyph codepoint='92' name='quoteright'/>
    <glyph codepoint='93' name='quotedblleft'/>
    <glyph codepoint='94' name='quotedblright'/>
    <glyph codepoint='95' name='bullet'/>
    <glyph codepoint='96' name='endash'/>
    <glyph codepoint='97' name='emdash'/>
    <glyph codepoint='99' name='trademark'/>
    <glyph codepoint='9a' name='scaron'/>
    <glyph codepoint='9b' name='guilsinglright'/>
    <glyph codepoint='9c' name='sacute'/>
    <glyph codepoint='9d' name='tcaron'/>
    <glyph codepoint='9e' name='zcaron'/>
    <glyph codepoint='9f' name='zacute'/>
    <glyph codepoint='a1' name='caron'/>
    <glyph codepoint='a2' name='breve'/>
    <glyph codepoint='a3' name='Lslash'/>
    <glyph codepoint='a4' name='currency'/>
    <glyph codepoint='a5' name='Aogonek'/>
    <glyph codepoint='a6' name='brokenbar'/>
    <glyph codepoint='a7' name='section'/>
    <glyph codepoint='a8' name='dieresis'/>
    <glyph codepoint='a9' name='copyright'/>
    <glyph codepoint='aa' name='Scommaaccent'/>
    <glyph codepoint='ab' name='guillemotleft'/>
    <glyph codepoint='ac' name='logicalnot'/>
    <glyph codepoint='ae' name='registered'/>
    <glyph codepoint='af' name='Zdotaccent'/>
    <glyph codepoint='b0' name='degree'/>
    <glyph codepoint='b1' name='plusminus'/>
    <glyph codepoint='b2' name='ogonek'/>
    <glyph codepoint='b3' name='lslash'/>
    <glyph codepoint='b4' name='acute'/>
    <glyph codepoint='b5' name='mu'/>
    <glyph codepoint='b6' name='paragraph'/>
    <glyph codepoint='b7' name='periodcentered'/>
    <glyph codepoint='b8' name='cedilla'/>
    <glyph codepoint='b9' name='aogonek'/>
    <glyph codepoint='ba' name='scommaaccent'/>
    <glyph codepoint='bb' name='guillemotright'/>
    <glyph codepoint='bc' name='Lcaron'/>
    <glyph codepoint='bd' name='hungarumlaut'/>
    <glyph codepoint='be' name='lcaron'/>
    <glyph codepoint='bf' name='zdotaccent'/>
    <glyph codepoint='c0' name='Racute'/>
    <glyph codepoint='c1' name='Aacute'/>
    <glyph codepoint='c2' name='Acircumflex'/>
    <glyph codepoint='c3' name='Abreve'/>
    <glyph codepoint='c4' name='Adieresis'/>
    <glyph codepoint='c5' name='Lacute'/>
    <glyph codepoint='c6' name='Cacute'/>
    <glyph codepoint='c7' name='Ccedilla'/>
    <glyph codepoint='c8' name='Ccaron'/>
    <glyph codepoint='c9' name='Eacute'/>
    <glyph codepoint='ca' name='Eogonek'/>
    <glyph codepoint='cb' name='Edieresis'/>
    <glyph codepoint='cc' name='Ecaron'/>
    <glyph codepoint='cd' name='Iacute'/>
    <glyph codepoint='ce' name='Icircumflex'/>
    <glyph codepoint='cf' name='Dcaron'/>
    <glyph codepoint='d0' name='Dcroat'/>
    <glyph codepoint='d1' name='Nacute'/>
    <glyph codepoint='d2' name='Ncaron'/>
    <glyph codepoint='d3' name='Oacute'/>
    <glyph codepoint='d4' name='Ocircumflex'/>
    <glyph codepoint='d5' name='Ohungarumlaut'/>
    <glyph codepoint='d6' name='Odieresis'/>
    <glyph codepoint='d7' name='multiply'/>
    <glyph codepoint='d8' name='Rcaron'/>
    <glyph codepoint='d9' name='Uring'/>
    <glyph codepoint='da' name='Uacute'/>
    <glyph codepoint='db' name='Uhungarumlaut'/>
    <glyph codepoint='dc' name='Udieresis'/>
    <glyph codepoint='dd' name='Yacute'/>
    <glyph codepoint='de' name='Tcommaaccent'/>
    <glyph codepoint='df' name='germandbls'/>
    <glyph codepoint='e0' name='racute'/>
    <glyph codepoint='e1' name='aacute'/>
    <glyph codepoint='e2' name='acircumflex'/>
    <glyph codepoint='e3' name='abreve'/>
    <glyph codepoint='e4' name='adieresis'/>
    <glyph codepoint='e5' name='lacute'/>
    <glyph codepoint='e6' name='cacute'/>
    <glyph codepoint='e7' name='ccedilla'/>
    <glyph codepoint='e8' name='ccaron'/>
    <glyph codepoint='e9' name='eacute'/>
    <glyph codepoint='ea' name='eogonek'/>
    <glyph codepoint='eb' name='edieresis'/>
    <glyph codepoint='ec' name='ecaron'/>
    <glyph codepoint='ed' name='iacute'/>
    <glyph codepoint='ee' name='icircumflex'/>
    <glyph codepoint='ef' name='dcaron'/>
    <glyph codepoint='f0' name='dcroat'/>
    <glyph codepoint='f1' name='nacute'/>
    <glyph codepoint='f2' name='ncaron'/>
    <glyph codepoint='f3' name='oacute'/>
    <glyph codepoint='f4' name='ocircumflex'/>
    <glyph codepoint='f5' name='ohungarumlaut'/>
    <glyph codepoint='f6' name='odieresis'/>
    <glyph codepoint='f7' name='divide'/>
    <glyph codepoint='f8' name='rcaron'/>
    <glyph codepoint='f9' name='uring'/>
    <glyph codepoint='fa' name='uacute'/>
    <glyph codepoint='fb' name='uhungarumlaut'/>
    <glyph codepoint='fc' name='udieresis'/>
    <glyph codepoint='fd' name='yacute'/>
    <glyph codepoint='fe' name='tcommaaccent'/>
    <glyph codepoint='ff' name='dotaccent'/>
  </encoding>
  <encoding id='MacRomanEncoding' constant="MAC_ROMAN_ENCODING" glyphlist='AGL'>
    <glyph codepoint='20' name='space'/>
    <glyph codepoint='21' name='exclam'/>
    <glyph codepoint='22' name='quotedbl'/>
    <glyph codepoint='23' name='numbersign'/>
    <glyph codepoint='24' name='dollar'/>
    <glyph codepoint='25' name='percent'/>
    <glyph codepoint='26' name='ampersand'/>
    <glyph codepoint='27' name='quotesingle'/>
    <glyph codepoint='28' name='parenleft'/>
    <glyph codepoint='29' name='parenright'/>
    <glyph codepoint='2a' name='asterisk'/>
    <glyph codepoint='2b' name='plus'/>
    <glyph codepoint='2c' name='comma'/>
    <glyph codepoint='2d' name='hyphen'/>
    <glyph codepoint='2e' name='period'/>
    <glyph codepoint='2f' name='slash'/>
    <glyph codepoint='30' name='zero'/>
    <glyph codepoint='31' name='one'/>
    <glyph codepoint='32' name='two'/>
    <glyph codepoint='33' name='three'/>
    <glyph codepoint='34' name='four'/>
    <glyph codepoint='35' name='five'/>
    <glyph codepoint='36' name='six'/>
    <glyph codepoint='37' name='seven'/>
    <glyph codepoint='38' name='eight'/>
    <glyph codepoint='39' name='nine'/>
    <glyph codepoint='3a' name='colon'/>
    <glyph codepoint='3b' name='semicolon'/>
    <glyph codepoint='3c' name='less'/>
    <glyph codepoint='3d' name='equal'/>
    <glyph codepoint='3e' name='greater'/>
    <glyph codepoint='3f' name='question'/>
    <glyph codepoint='40' name='at'/>
    <glyph codepoint='41' name='A'/>
    <glyph codepoint='42' name='B'/>
    <glyph codepoint='43' name='C'/>
    <glyph codepoint='44' name='D'/>
    <glyph codepoint='45' name='E'/>
    <glyph codepoint='46' name='F'/>
    <glyph codepoint='47' name='G'/>
    <glyph codepoint='48' name='H'/>
    <glyph codepoint='49' name='I'/>
    <glyph codepoint='4a' name='J'/>
    <glyph codepoint='4b' name='K'/>
    <glyph codepoint='4c' name='L'/>
    <glyph codepoint='4d' name='M'/>
    <glyph codepoint='4e' name='N'/>
    <glyph codepoint='4f' name='O'/>
    <glyph codepoint='50' name='P'/>
    <glyph codepoint='51' name='Q'/>
    <glyph codepoint='52' name='R'/>
    <glyph codepoint='53' name='S'/>
    <glyph codepoint='54' name='T'/>
    <glyph codepoint='55' name='U'/>
    <glyph codepoint='56' name='V'/>
    <glyph codepoint='57' name='W'/>
    <glyph codepoint='58' name='X'/>
    <glyph codepoint='59' name='Y'/>
    <glyph codepoint='5a' name='Z'/>
    <glyph codepoint='5b' name='bracketleft'/>
    <glyph codepoint='5c' name='backslash'/>
    <glyph codepoint='5d' name='bracketright'/>
    <glyph codepoint='5e' name='asciicircum'/>
    <glyph codepoint='5f' name='underscore'/>
    <glyph codepoint='60' name='grave'/>
    <glyph codepoint='61' name='a'/>
    <glyph codepoint='62' name='b'/>
    <glyph codepoint='63' name='c'/>
    <glyph codepoint='64' name='d'/>
    <glyph codepoint='65' name='e'/>
    <glyph codepoint='66' name='f'/>
    <glyph codepoint='67' name='g'/>
    <glyph codepoint='68' name='h'/>
    <glyph codepoint='69' name='i'/>
    <glyph codepoint='6a' name='j'/>
    <glyph codepoint='6b' name='k'/>
    <glyph codepoint='6c' name='l'/>
    <glyph codepoint='6d' name='m'/>
    <glyph codepoint='6e' name='n'/>
    <glyph codepoint='6f' name='o'/>
    <glyph codepoint='70' name='p'/>
    <glyph codepoint='71' name='q'/>
    <glyph codepoint='72' name='r'/>
    <glyph codepoint='73' name='s'/>
    <glyph codepoint='74' name='t'/>
    <glyph codepoint='75' name='u'/>
    <glyph codepoint='76' name='v'/>
    <glyph codepoint='77' name='w'/>
    <glyph codepoint='78' name='x'/>
    <glyph codepoint='79' name='y'/>
    <glyph codepoint='7b' name='braceleft'/>
    <glyph codepoint='7c' name='bar'/>
    <glyph codepoint='7d' name='braceright'/>
    <glyph codepoint='7e' name='asciitilde'/>
    <glyph codepoint='80' name='Adieresis'/>
    <glyph codepoint='81' name='Aring'/>
    <glyph codepoint='82' name='Ccedilla'/>
    <glyph codepoint='83' name='Eacute'/>
    <glyph codepoint='84' name='Ntilde'/>
    <glyph codepoint='85' name='Odieresis'/>
    <glyph codepoint='86' name='Udieresis'/>
    <glyph codepoint='87' name='aacute'/>
    <glyph codepoint='88' name='agrave'/>
    <glyph codepoint='89' name='acircumflex'/>
    <glyph codepoint='8a' name='adieresis'/>
    <glyph codepoint='8b' name='atilde'/>
    <glyph codepoint='8c' name='aring'/>
    <glyph codepoint='8d' name='ccedilla'/>
    <glyph codepoint='8e' name='eacute'/>
    <glyph codepoint='8f' name='egrave'/>
    <glyph codepoint='90' name='ecircumflex'/>
    <glyph codepoint='91' name='edieresis'/>
    <glyph codepoint='92' name='iacute'/>
    <glyph codepoint='93' name='igrave'/>
    <glyph codepoint='94' name='icircumflex'/>
    <glyph codepoint='95' name='idieresis'/>
    <glyph codepoint='96' name='ntilde'/>
    <glyph codepoint='97' name='oacute'/>
    <glyph codepoint='98' name='ograve'/>
    <glyph codepoint='99' name='ocircumflex'/>
    <glyph codepoint='9a' name='odieresis'/>
    <glyph codepoint='9b' name='otilde'/>
    <glyph codepoint='9c' name='uacute'/>
    <glyph codepoint='9d' name='ugrave'/>